### ISSUE TITLE
[BUG] Onestepcheckout.com compatibility

### ISSUE THREAD

**Issue by Paulsky** [postcodeservice/postcode-magento2#52]
**To Reproduce**
1. Enable Onestepcheckout
2. Sort and enable postcode, tig_housenumber, tig_housenumber_additional and tig_street field

**Expected result**
Postcode field is rendered before tig_housenumber and tig_housenumber_additional

**Actual result**
Postccode field is sometimes rendered before tig_housenumber, sometimes completly elsewhere

**Workaround**
None, I'm wrting some JS for fixing this bug and other TIG bugs

- Magento version: [Magento 2.4.5]
- PHP version: [8.1]

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

We do support some one-step checkouts, which one-step checkout do you got? Do you use the https://www.onestepcheckout.com/ extension? Because that is one we do not support, unfortunately.

If you use another one-step checkout we would like to here which checkout and what version of this checkout.

Have a great day,
Jeffrey

**Comment by Paulsky** [comment]
Yes I'm using Onestepcheckout.com. We weren't aware you didn't support that extension. Do you have this mentioned somewhere? When did you drop the support on this? Because you had an extension postcode-magento2-checkout-support to support it.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

Just a small update, I have placed support for onestepcheckout.com on our long term backlog, because in the future we do want to be compatible with the checkout. I will link this GitHub issue to our backlog issue as an upvote on the feature. 

If you have other onestepcheckouts available, like the amasty or mageplaza checkout, these checkouts should work with the postcode extension. 

Have a great day,
Jeffrey

**Comment by erwinromkes** [comment]
@tig-jeffreybranderhorst do you maybe made some progression on this issue?

**Comment by tig-support** [comment]
Hi @erwinromkes, I don’t have an update on this at the moment. It is on our long term backlog.

**Comment by schldwcht** [comment]
Hi @Paulsky, @erwinromkes 
I wanted to inform you that, after careful consideration, we have decided not to support the OSC of OneStepCheckout.com at this time. Although we may revisit this decision in the future, we have decided to close this issue for the time being.

Thank you for your understanding and please let us know if you have any questions or concerns. Have a great day!

Best regards,
Joost
